{
  description = "nide - A productive development tool for Nim";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      nimToolchain = pkgs.fetchzip {
        url = "https://github.com/nim-lang/nightlies/releases/download/2026-02-23-version-2-2-4f500679b196fad944caa50a753f5bbfaefda001/nim-2.2.8-linux_x64.tar.xz";
        hash = "sha256-nPkDSy/OHq3iN9QLZ1M+qVlFHZo/EaSr/DOzihTYjBw=";
      };
      nimble = pkgs.writeShellApplication {
        name = "nimble";
        text = ''
          set -e

          if [ -n "''${NIDE_ROOT:-}" ]; then
            exec ${nimToolchain}/bin/nimble \
              --nim:${nimToolchain}/bin/nim \
              --useSystemNim \
              --nimbleDir:"$NIDE_ROOT/nimbledeps" \
              "$@"
          fi

          exec ${nimToolchain}/bin/nimble \
            --nim:${nimToolchain}/bin/nim \
            --useSystemNim \
            "$@"
        '';
      };
      prepareNimble = pkgs.writeShellApplication {
        name = "nide-prepare-nimble";
        runtimeInputs = [ nimble pkgs.coreutils pkgs.git ];
        text = ''
          set -euo pipefail

          cd "$NIDE_ROOT"
          mkdir -p "$NIMBLE_DIR"

          current_state="$(
            {
              printf '%s\n' 'toolchain:nim-2.2.8-linux_x64-system:paths-v2';
              cksum nide.nimble nimble.lock config.nims 2>/dev/null || true
            }
          )"
          state_file="$NIMBLE_DIR/.nide-deps-state"
          paths_file="$NIMBLE_DIR/nimble.paths.nims"
          needs_bootstrap=0
          paths_ok=1

          if [ ! -f "$paths_file" ]; then
            paths_ok=0
          fi

          if [ ! -f "$state_file" ] || [ "$(cat "$state_file")" != "$current_state" ]; then
            needs_bootstrap=1
          fi

          if ! nimble path seaqt >/dev/null 2>&1; then
            needs_bootstrap=1
          fi

          if ! nimble path db_connector >/dev/null 2>&1; then
            needs_bootstrap=1
          fi

          for pkg in seaqt unittest2 db_connector toml_serialization stew results serialization faststreams; do
            pkg_path="$(nimble path "$pkg" 2>/dev/null | tail -n 1 || true)"
            case "$pkg_path" in
              "$NIMBLE_DIR"/*) ;;
              *) paths_ok=0 ;;
            esac
            if [ ! -d "$pkg_path" ]; then
              paths_ok=0
            fi
          done

          if [ "$paths_ok" -ne 1 ]; then
            needs_bootstrap=1
          fi

          if [ "$needs_bootstrap" -eq 1 ]; then
            echo "[nide] Syncing Nimble dependencies into $NIMBLE_DIR"
            nimble install -y -d
            {
              echo "# Generated by nide-prepare-nimble"
              for pkg in serialization stew toml_serialization seaqt unittest2 faststreams db_connector results; do
                pkg_path="$(nimble path "$pkg" 2>/dev/null | tail -n 1)"
                rel_path="''${pkg_path#"$NIMBLE_DIR"/}"
                echo "switch(\"path\", thisDir() & \"/$rel_path\")"
              done
            } > "$paths_file"
            printf '%s\n' "$current_state" > "$state_file"
          fi
        '';
      };

      buildFlatpak = pkgs.writeShellApplication {
        name = "build-flatpak";
        runtimeInputs = with pkgs; [ flatpak-builder flatpak librsvg patchelf ] ++ [ nimToolchain ];
        text = ''
          set -euo pipefail

          MANIFEST="flatpak/io.github.dneumann42.Nide.yml"
          BUILD_DIR=".flatpak-build"
          REPO_DIR=".flatpak-repo"

          echo "Building nide binary..."
          _pkgbin=$(mktemp -d)
          printf '#!/bin/sh\nPKG_CONFIG_PATH=/usr/lib/pkgconfig exec /usr/bin/pkg-config "$@"\n' \
            > "$_pkgbin/pkg-config"
          chmod +x "$_pkgbin/pkg-config"
          export PATH="$_pkgbin:$PATH"
          rm -rf ~/.cache/nim/nide_r
          nim cpp -d:release --passL:"-L/usr/lib -Wl,-rpath-link,/usr/lib" --out:nide src/nide.nim
          patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 nide
          patchelf --set-rpath "" nide

          echo "Adding Flathub remote (if missing)..."
          flatpak remote-add --user --if-not-exists flathub \
            https://flathub.org/repo/flathub.flatpakrepo || true

          echo "Installing KDE 6.10 runtime (if missing)..."
          flatpak install --user --noninteractive flathub \
            org.kde.Platform//6.10 org.kde.Sdk//6.10 || true

          echo "Converting icon to PNG..."
          rsvg-convert -w 128 -h 128 data/icons/io.github.dneumann42.Nide.svg \
            -o data/icons/io.github.dneumann42.Nide.png

          echo "Building flatpak..."
          flatpak-builder \
            --force-clean \
            --disable-rofiles-fuse \
            --user \
            --install-deps-from=flathub \
            --repo="$REPO_DIR" \
            "$BUILD_DIR" \
            "$MANIFEST"

          echo "Bundling nide.flatpak..."
          flatpak build-bundle \
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
            "$REPO_DIR" \
            nide.flatpak \
            io.github.dneumann42.Nide

          echo "Done: nide.flatpak"
        '';
      };
    in {
      packages.${system}.build-flatpak = buildFlatpak;

      apps.${system}.build-flatpak = {
        type = "app";
        program = "${buildFlatpak}/bin/build-flatpak";
      };

      devShells.${system}.default =
        let
          libs = with pkgs; [
            qt6.qtbase
            qt6.qtsvg
            sqlite
            pcre
          ];
        in
        pkgs.mkShell {
          buildInputs = libs ++ (with pkgs; [ pkg-config flatpak-builder flatpak git ]) ++ [ nimToolchain nimble ];
          shellHook = ''
            export NIDE_ROOT="$PWD"
            export NIMBLE_DIR="$NIDE_ROOT/nimbledeps"
            export PATH="${nimble}/bin:${nimToolchain}/bin:$NIMBLE_DIR/bin:$PATH"
            export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath libs}:$LD_LIBRARY_PATH
            export QT_QPA_PLATFORM_PLUGIN_PATH="${pkgs.qt6.qtbase}/lib/qt-6/plugins/platforms"
            export PKG_CONFIG_PATH="${pkgs.qt6.qtbase.dev}/lib/pkgconfig:${pkgs.qt6.qtsvg.dev}/lib/pkgconfig:${pkgs.sqlite.dev}/lib/pkgconfig:$PKG_CONFIG_PATH"
            ${prepareNimble}/bin/nide-prepare-nimble
          '';
        };
    };
}
