[meta]
name = "Dracula"
variant = "dark"

[editor]
background = "#282a36"
foreground = "#f8f8f2"
lineNumber = "#6272a4"
lineNumberBg = "#282a36"
selection = "#44475a"
currentLine = "#343746"
primary = "#bd93f9"

[syntax]
keyword = "#ff79c6"
keywordBold = true
keywordItalic = false
controlFlow = "#ffb86c"
controlFlowBold = false
controlFlowItalic = false
type = "#8be9fd"
typeBold = false
typeItalic = true
builtinType = "#8be9fd"
specialVar = "#ffb86c"
string = "#f1fa8c"
charLit = "#bd93f9"
number = "#bd93f9"
comment = "#6272a4"
commentItalic = true
docComment = "#6272a4"
docCommentItalic = true
blockComment = "#6272a4"
pragma = "#50fa7b"
operator = "#ff79c6"
funcName = "#50fa7b"
