[meta]
name = "Gruvbox Dark"
variant = "dark"

[editor]
background = "#1d2021"
foreground = "#ebdbb2"
lineNumber = "#665c54"
lineNumberBg = "#1d2021"
selection = "#504945"
currentLine = "#282828"
primary = "#d79921"

[syntax]
keyword = "#fb4934"
keywordBold = true
keywordItalic = false
controlFlow = "#fe8019"
controlFlowBold = false
controlFlowItalic = false
type = "#8ec07c"
typeBold = false
typeItalic = false
builtinType = "#8ec07c"
specialVar = "#d3869b"
string = "#b8bb26"
charLit = "#b8bb26"
number = "#d3869b"
comment = "#928374"
commentItalic = true
docComment = "#928374"
docCommentItalic = true
blockComment = "#928374"
pragma = "#fabd2f"
operator = "#ebdbb2"
funcName = "#83a598"
