[meta]
name = "Rosé Pine Dawn"
variant = "light"

[editor]
background = "#faf4ed"
foreground = "#575279"
lineNumber = "#9893a5"
lineNumberBg = "#fffaf3"
selection = "#e6ddcf"
currentLine = "#f2e9e1"
primary = "#286983"

[syntax]
keyword = "#b4637a"
keywordBold = true
keywordItalic = false
controlFlow = "#d7827e"
controlFlowBold = false
controlFlowItalic = false
type = "#56949f"
typeBold = false
typeItalic = false
builtinType = "#56949f"
specialVar = "#ea9d34"
string = "#797593"
charLit = "#797593"
number = "#ea9d34"
comment = "#9893a5"
commentItalic = true
docComment = "#9893a5"
docCommentItalic = true
blockComment = "#9893a5"
pragma = "#907aa9"
operator = "#575279"
funcName = "#286983"
