[meta]
name = "Tokyo Night"
variant = "dark"

[editor]
background = "#1a1b26"
foreground = "#c0caf5"
lineNumber = "#565f89"
lineNumberBg = "#1a1b26"
selection = "#33467c"
currentLine = "#24283b"
primary = "#7aa2f7"

[syntax]
keyword = "#bb9af7"
keywordBold = true
keywordItalic = false
controlFlow = "#f7768e"
controlFlowBold = false
controlFlowItalic = false
type = "#73daca"
typeBold = false
typeItalic = false
builtinType = "#73daca"
specialVar = "#ff9e64"
string = "#9ece6a"
charLit = "#9ece6a"
number = "#ff9e64"
comment = "#565f89"
commentItalic = true
docComment = "#565f89"
docCommentItalic = true
blockComment = "#565f89"
pragma = "#7dcfff"
operator = "#c0caf5"
funcName = "#7aa2f7"
