[meta]
name = "VS Code Dark+"
variant = "dark"

[editor]
background = "#000000"
foreground = "#d4d4d4"
lineNumber = "#858585"
lineNumberBg = "#000000"
selection = "#264f78"
currentLine = "#2a2d2e"
primary = "#2a82da"

[syntax]
keyword = "#569cd6"
keywordBold = true
keywordItalic = false
controlFlow = "#c586c0"
controlFlowBold = false
controlFlowItalic = false
type = "#4ec9b0"
typeBold = false
typeItalic = false
builtinType = "#4ec9b0"
specialVar = "#9cdcfe"
string = "#ce9178"
charLit = "#ce9178"
number = "#b5cea8"
comment = "#6a9955"
commentItalic = true
docComment = "#608b4e"
docCommentItalic = true
blockComment = "#6a9955"
pragma = "#9cdcfe"
operator = "#d4d4d4"
funcName = "#dcdcaa"
