[meta]
name = "Monokai"
variant = "dark"

[editor]
background = "#272822"
foreground = "#f8f8f2"
lineNumber = "#90908a"
lineNumberBg = "#272822"
selection = "#49483e"
currentLine = "#3e3d32"

[syntax]
keyword = "#f92672"
keywordBold = true
keywordItalic = false
type = "#66d9ef"
typeBold = false
typeItalic = true
builtinType = "#66d9ef"
string = "#e6db74"
charLit = "#e6db74"
number = "#ae81ff"
comment = "#75715e"
commentItalic = true
docComment = "#75715e"
docCommentItalic = true
blockComment = "#75715e"
pragma = "#a6e22e"
operator = "#f92672"
funcName = "#a6e22e"
