[meta]
name = "Nord"
variant = "dark"

[editor]
background = "#000000"
foreground = "#d8dee9"
lineNumber = "#4c566a"
lineNumberBg = "#000000"
selection = "#434c5e"
currentLine = "#3b4252"
primary = "#88c0d0"

[syntax]
keyword = "#81a1c1"
keywordBold = true
keywordItalic = false
type = "#8fbcbb"
typeBold = false
typeItalic = false
builtinType = "#8fbcbb"
string = "#a3be8c"
charLit = "#a3be8c"
number = "#b48ead"
comment = "#616e88"
commentItalic = true
docComment = "#616e88"
docCommentItalic = true
blockComment = "#616e88"
pragma = "#ebcb8b"
operator = "#81a1c1"
funcName = "#88c0d0"
