[meta]
name = "Solarized Dark"
variant = "dark"

[editor]
background = "#000000"
foreground = "#839496"
lineNumber = "#586e75"
lineNumberBg = "#000000"
selection = "#073642"
currentLine = "#073642"
primary = "#268bd2"

[syntax]
keyword = "#859900"
keywordBold = true
keywordItalic = false
controlFlow = "#cb4b16"
controlFlowBold = false
controlFlowItalic = false
type = "#268bd2"
typeBold = false
typeItalic = false
builtinType = "#268bd2"
specialVar = "#2aa198"
string = "#2aa198"
charLit = "#2aa198"
number = "#d33682"
comment = "#586e75"
commentItalic = true
docComment = "#657b83"
docCommentItalic = true
blockComment = "#586e75"
pragma = "#b58900"
operator = "#93a1a1"
funcName = "#268bd2"
